modLoader="javafml"

loaderVersion="[36,)"

license="All rights reserved"

issueTrackerURL="https://github.com/pWn3d1337/Techguns_1.14/issues"

[[mods]]
itemIcon="techguns:heavy_cloth"

configBackground="techguns:textures/blocks/airmarker"

modId="techguns"

version="2.0.2.1"

displayName="Techguns"

displayURL="https://www.curseforge.com/minecraft/mc-mods/techguns"

credits="Thanks for this mod goes to pWn3d_1337 for making all versions bellow 1.16.5"

authors=["RedRoseWarrior1 aka DevMaster1015"]

description='''
Guns, Armors, NPCs, Machines and more'''

# Base Forge
[[dependencies.techguns]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

# Base Minecraft
[[dependencies.techguns]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17]"
ordering="NONE"
side="BOTH"
